defaults: &defaults
  working_directory: ~/viola
  docker:
    - image: circleci/node:8

version: 2
jobs:
  ###
  ### checkout
  ###
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - viola-v1-dependencies-{{ checksum "package.json" }}
            - viola-v1-dependencies-
      - restore_cache:
          keys:
            - bramble-v1-dependencies-{{ checksum "brackets/package.json" }}
            - bramble-v1-dependencies-
      - restore_cache:
          keys:
            - bramble-src-v1-dependencies-{{ checksum "brackets/src/package.json" }}
            - bramble-src-v1-dependencies-

      - run: npm install
      - save_cache:
          key: viola-v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: bramble-v1-dependencies-{{ checksum "brackets/package.json" }}
          paths:
            - brackets/node_modules
      - save_cache:
          key: bramble-src-v1-dependencies-{{ checksum "brackets/src/package.json" }}
          paths:
            - brackets/src/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  ###
  ### build-bramble-stage
  ###
  build-bramble-stage:
    <<: *defaults
    environment:
      - REACT_APP_BRAMBLE_HOST_URL: https://draft-editor.viola.pub/index.html

    steps:
      - attach_workspace:
          at: .
      - run: npm run bramble:build
      - persist_to_workspace:
          root: .
          paths:
            - brackets/dist/*

  ###
  ### build-bramble-prod
  build-bramble-prod:
    <<: *defaults
    environment:
      - REACT_APP_BRAMBLE_HOST_URL: https://editor.viola.pub/index.html

    steps:
      - attach_workspace:
          at: .
      - run: npm run bramble:build
      - persist_to_workspace:
          root: .
          paths:
            - brackets/dist/*

  ###
  ### build-viola-stage
  ###
  build-viola-stage:
    <<: *defaults
    environment:
      - REACT_APP_BRAMBLE_HOST_URL: https://draft-editor.viola.pub/index.html
      - REACT_APP_PRINT_PAGE_HOST_URL: https://draft-editor.viola.pub/thirdparty/viola-savepdf/index.html
      - REACT_APP_VFS_ROOT_URL: https://draft-editor.viola.pub/vfs/
      - REACT_APP_VIOLA_HOMEPAGE: https://viola.pub
      - REACT_APP_CELLO_HOST_URL: https://staging.viola.pub

    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*

  ###
  ### build-viola-prod
  ###
  build-viola-prod:
    <<: *defaults
    environment:
      - REACT_APP_BRAMBLE_HOST_URL: https://editor.viola.pub/index.html
      - REACT_APP_PRINT_PAGE_HOST_URL: https://editor.viola.pub/thirdparty/viola-savepdf/index.html
      - REACT_APP_VFS_ROOT_URL: https://editor.viola.pub/vfs/
      - REACT_APP_VIOLA_HOMEPAGE: https://viola.pub
      - REACT_APP_CELLO_HOST_URL: https://viola.pub

    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*

  ###
  ### deploy-stage
  ###
  deploy-stage:
    <<: *defaults
    docker:
      - image: xueshanf/awscli

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy viola app to staging
          command: aws s3 sync --delete build s3://draft-writing.viola.pub
      - run:
          name: Deploy bramble app to staging
          command: aws s3 sync --delete brackets/dist s3://draft-editor.viola.pub

  ###
  ### deploy-prod
  ###
  deploy-prod:
    <<: *defaults
    docker:
      - image: xueshanf/awscli

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy viola app to production
          command: aws s3 sync --delete build s3://writing.viola.pub
      - run:
          name: Deploy bramble app to production
          command: aws s3 sync --delete brackets/dist s3://editor.viola.pub

workflows:
  version: 2
  build-deploy:
    jobs:
    # staging
      - checkout:
          filters:
            branches:
              only:
                - develop
                - master
      - build-bramble-stage:
          requires:
            - checkout
          filters:
            branches:
              only: develop
      - build-viola-stage:
          requires:
            - build-bramble-stage
          filters:
            branches:
              only: develop
      - deploy-stage:
          requires:
            - build-viola-stage
          filters:
            branches:
              only: develop

    # production
      - build-bramble-prod:
          requires:
            - checkout
          filters:
            branches:
              only: master
      - build-viola-prod:
          requires:
            - build-bramble-prod
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build-viola-prod
          filters:
            branches:
              only: master
